component: express
name: express-VmMR4W3jQ
org: '1256505457'
app: sign-server
stage: test
inputs:
  src:
    src: ./
    exclude:
      - docs
      - _tests_
      - .github
      # - .env
      # - node_modules/**
  region: ap-chengdu
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    eip: false
    timeout: 3
    memorySize: 128
    environment:
      Variables:
        ENV_FIRST: env1
        ENV_SECOND: env2
  layers:
    - name: '${output:${stage}:${app}:sign-server-layer.name}'
      version: '${output:${stage}:${app}:sign-server-layer.version}'
